CREATE TABLE IF NOT EXISTS `content_blocks` (
    `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `block_key`  VARCHAR(120) NOT NULL UNIQUE,
    `label`      VARCHAR(190) NOT NULL DEFAULT '',
    `value`      TEXT NULL,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;